spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  r2dbc:
    url: ${R2DBC_URL:r2dbc:h2:mem:///alumnodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${R2DBC_USERNAME:sa}
    password: ${R2DBC_PASSWORD:password}
  h2:
    console:
      enabled: true
  main:
    web-application-type: reactive